/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [V1](/docs/tokens/v1) | | [V2](/docs/tokens/v2) | | [V1 Deprecated](/docs/tokens/v1) | 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { MintInformation } from '../types';
// @ts-ignore
import type { SearchGet400Response } from '../types';
/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns an array of mints and their information for the given category and interval 
         * @summary category
         * @param {CategoryIntervalGetCategoryEnum} category - Top tokens in different trading categories - The result filters out generic top tokens like SOL, USDC, etc - Default to 50 mints in response 
         * @param {CategoryIntervalGetIntervalEnum} interval - Query by time interval for more accuracy 
         * @param {number} [limit] - Maximum number of results to return (default 50, max 100) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryIntervalGet: async (category: CategoryIntervalGetCategoryEnum, interval: CategoryIntervalGetIntervalEnum, limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'category' is not null or undefined
            assertParamExists('categoryIntervalGet', 'category', category)
            // verify required parameter 'interval' is not null or undefined
            assertParamExists('categoryIntervalGet', 'interval', interval)
            const localVarPath = `/{category}/{interval}`
                .replace(`{${"category"}}`, encodeURIComponent(String(category)))
                .replace(`{${"interval"}}`, encodeURIComponent(String(interval)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns an array of mints that recently had their **first created pool** - Default to 30 mints in response 
         * @summary recent
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recentGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/recent`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Request a search by token\'s symbol, name or mint address 
         * @summary search
         * @param {string} query - Search for a token and its information by its symbol, name or mint address - Comma-separate to ONLY search for multiple mint addresses - Limit to 100 mint addresses in query - Default to 20 mints in response when searching via symbol or name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchGet: async (query: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('searchGet', 'query', query)
            const localVarPath = `/search`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Request an array of mints and their information by a tag - Note that this will return the entire array of existing mints that belongs to the tag. 
         * @summary tag
         * @param {TagGetQueryEnum} query 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagGet: async (query: TagGetQueryEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'query' is not null or undefined
            assertParamExists('tagGet', 'query', query)
            const localVarPath = `/tag`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (query !== undefined) {
                localVarQueryParameter['query'] = query;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns an array of mints and their information for the given category and interval 
         * @summary category
         * @param {CategoryIntervalGetCategoryEnum} category - Top tokens in different trading categories - The result filters out generic top tokens like SOL, USDC, etc - Default to 50 mints in response 
         * @param {CategoryIntervalGetIntervalEnum} interval - Query by time interval for more accuracy 
         * @param {number} [limit] - Maximum number of results to return (default 50, max 100) 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async categoryIntervalGet(category: CategoryIntervalGetCategoryEnum, interval: CategoryIntervalGetIntervalEnum, limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MintInformation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.categoryIntervalGet(category, interval, limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.categoryIntervalGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns an array of mints that recently had their **first created pool** - Default to 30 mints in response 
         * @summary recent
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async recentGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MintInformation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.recentGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.recentGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Request a search by token\'s symbol, name or mint address 
         * @summary search
         * @param {string} query - Search for a token and its information by its symbol, name or mint address - Comma-separate to ONLY search for multiple mint addresses - Limit to 100 mint addresses in query - Default to 20 mints in response when searching via symbol or name 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchGet(query: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MintInformation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchGet(query, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.searchGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Request an array of mints and their information by a tag - Note that this will return the entire array of existing mints that belongs to the tag. 
         * @summary tag
         * @param {TagGetQueryEnum} query 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tagGet(query: TagGetQueryEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<MintInformation>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tagGet(query, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.tagGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Returns an array of mints and their information for the given category and interval 
         * @summary category
         * @param {DefaultApiCategoryIntervalGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        categoryIntervalGet(requestParameters: DefaultApiCategoryIntervalGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<MintInformation>> {
            return localVarFp.categoryIntervalGet(requestParameters.category, requestParameters.interval, requestParameters.limit, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns an array of mints that recently had their **first created pool** - Default to 30 mints in response 
         * @summary recent
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        recentGet(options?: RawAxiosRequestConfig): AxiosPromise<Array<MintInformation>> {
            return localVarFp.recentGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Request a search by token\'s symbol, name or mint address 
         * @summary search
         * @param {DefaultApiSearchGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchGet(requestParameters: DefaultApiSearchGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<MintInformation>> {
            return localVarFp.searchGet(requestParameters.query, options).then((request) => request(axios, basePath));
        },
        /**
         * Request an array of mints and their information by a tag - Note that this will return the entire array of existing mints that belongs to the tag. 
         * @summary tag
         * @param {DefaultApiTagGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tagGet(requestParameters: DefaultApiTagGetRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<MintInformation>> {
            return localVarFp.tagGet(requestParameters.query, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for categoryIntervalGet operation in DefaultApi.
 * @export
 * @interface DefaultApiCategoryIntervalGetRequest
 */
export interface DefaultApiCategoryIntervalGetRequest {
    /**
     * - Top tokens in different trading categories - The result filters out generic top tokens like SOL, USDC, etc - Default to 50 mints in response 
     * @type {'toporganicscore' | 'toptraded' | 'toptrending'}
     * @memberof DefaultApiCategoryIntervalGet
     */
    readonly category: CategoryIntervalGetCategoryEnum

    /**
     * - Query by time interval for more accuracy 
     * @type {'5m' | '1h' | '6h' | '24h'}
     * @memberof DefaultApiCategoryIntervalGet
     */
    readonly interval: CategoryIntervalGetIntervalEnum

    /**
     * - Maximum number of results to return (default 50, max 100) 
     * @type {number}
     * @memberof DefaultApiCategoryIntervalGet
     */
    readonly limit?: number
}

/**
 * Request parameters for searchGet operation in DefaultApi.
 * @export
 * @interface DefaultApiSearchGetRequest
 */
export interface DefaultApiSearchGetRequest {
    /**
     * - Search for a token and its information by its symbol, name or mint address - Comma-separate to ONLY search for multiple mint addresses - Limit to 100 mint addresses in query - Default to 20 mints in response when searching via symbol or name 
     * @type {string}
     * @memberof DefaultApiSearchGet
     */
    readonly query: string
}

/**
 * Request parameters for tagGet operation in DefaultApi.
 * @export
 * @interface DefaultApiTagGetRequest
 */
export interface DefaultApiTagGetRequest {
    /**
     * 
     * @type {'lst' | 'verified'}
     * @memberof DefaultApiTagGet
     */
    readonly query: TagGetQueryEnum
}

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Returns an array of mints and their information for the given category and interval 
     * @summary category
     * @param {DefaultApiCategoryIntervalGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public categoryIntervalGet(requestParameters: DefaultApiCategoryIntervalGetRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).categoryIntervalGet(requestParameters.category, requestParameters.interval, requestParameters.limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns an array of mints that recently had their **first created pool** - Default to 30 mints in response 
     * @summary recent
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public recentGet(options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).recentGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Request a search by token\'s symbol, name or mint address 
     * @summary search
     * @param {DefaultApiSearchGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public searchGet(requestParameters: DefaultApiSearchGetRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).searchGet(requestParameters.query, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Request an array of mints and their information by a tag - Note that this will return the entire array of existing mints that belongs to the tag. 
     * @summary tag
     * @param {DefaultApiTagGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public tagGet(requestParameters: DefaultApiTagGetRequest, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).tagGet(requestParameters.query, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const CategoryIntervalGetCategoryEnum = {
    TOPORGANICSCORE: 'toporganicscore',
    TOPTRADED: 'toptraded',
    TOPTRENDING: 'toptrending'
} as const;
export type CategoryIntervalGetCategoryEnum = typeof CategoryIntervalGetCategoryEnum[keyof typeof CategoryIntervalGetCategoryEnum];
/**
 * @export
 */
export const CategoryIntervalGetIntervalEnum = {
    _5M: '5m',
    _1H: '1h',
    _6H: '6h',
    _24H: '24h'
} as const;
export type CategoryIntervalGetIntervalEnum = typeof CategoryIntervalGetIntervalEnum[keyof typeof CategoryIntervalGetIntervalEnum];
/**
 * @export
 */
export const TagGetQueryEnum = {
    LST: 'lst',
    VERIFIED: 'verified'
} as const;
export type TagGetQueryEnum = typeof TagGetQueryEnum[keyof typeof TagGetQueryEnum];
