/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [Get Order](/docs/ultra/get-order) | | [Execute Order](/docs/ultra/execute-order) | 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ExecutePost200ResponseSwapEventsInner } from './execute-post200-response-swap-events-inner';

/**
 * 
 * @export
 * @interface ExecutePost200Response
 */
export interface ExecutePost200Response {
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'status': ExecutePost200ResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'signature'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'slot'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'error'?: string;
    /**
     * 
     * @type {number}
     * @memberof ExecutePost200Response
     */
    'code': number;
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'totalInputAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'totalOutputAmount'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'inputAmountResult'?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutePost200Response
     */
    'outputAmountResult'?: string;
    /**
     * 
     * @type {Array<ExecutePost200ResponseSwapEventsInner>}
     * @memberof ExecutePost200Response
     */
    'swapEvents'?: Array<ExecutePost200ResponseSwapEventsInner>;
}

export const ExecutePost200ResponseStatusEnum = {
    SUCCESS: 'Success',
    FAILED: 'Failed'
} as const;

export type ExecutePost200ResponseStatusEnum = typeof ExecutePost200ResponseStatusEnum[keyof typeof ExecutePost200ResponseStatusEnum];


