/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [Get Order](/docs/ultra/get-order) | | [Execute Order](/docs/ultra/execute-order) | 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderGet200ResponsePlatformFee } from './order-get200-response-platform-fee';
// May contain unused imports in some cases
// @ts-ignore
import type { OrderGet200ResponseRoutePlanInner } from './order-get200-response-route-plan-inner';

/**
 * 
 * @export
 * @interface OrderGet200Response
 */
export interface OrderGet200Response {
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'mode': string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'inputMint': string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'outputMint': string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'inAmount': string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'outAmount': string;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'inUsdValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'outUsdValue'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'priceImpact'?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'swapUsdValue'?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'otherAmountThreshold': string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'swapMode': string;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'slippageBps': number;
    /**
     * - Please use `priceImpact` field instead, this is still available only for backwards compatibility 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'priceImpactPct': string;
    /**
     * 
     * @type {Array<OrderGet200ResponseRoutePlanInner>}
     * @memberof OrderGet200Response
     */
    'routePlan': Array<OrderGet200ResponseRoutePlanInner>;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'referralAccount'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'feeMint'?: string;
    /**
     * - The fee includes either Ultra default fee or your integrator fee, depending on if referral and/or payer params are passed in - If `referralAccount`, `referralFee` (and `payer` if passed in) are passed in, the fee will be the integrator fee only - If no additional referral params are passed in, the fee will be the Ultra default fee only and can include additional fees for gasless support mechanism 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'feeBps': number;
    /**
     * 
     * @type {OrderGet200ResponsePlatformFee}
     * @memberof OrderGet200Response
     */
    'platformFee': OrderGet200ResponsePlatformFee;
    /**
     * - The number of lamports the `taker`, `maker` (JupiterZ\'s MM) or `payer` has to pay for the base network fee, if a valid transaction is returned. 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'signatureFeeLamports': number;
    /**
     * - The public key of the account that will cover the signature fee, it can be either `taker`, `maker` (JupiterZ\'s MM) or `payer` if passed in 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'signatureFeePayer': string | null;
    /**
     * - The number of lamports the `taker`, `maker` (JupiterZ\'s MM) or `payer` has to pay for higher priority landing, if a valid transaction is returned - Includes priority fees and tips for services such as Jito, etc, if any 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'prioritizationFeeLamports': number;
    /**
     * - The public key of the account that will cover the prioritization fee, it can be either `taker`, `maker` (JupiterZ\'s MM) or `payer` if passed in 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'prioritizationFeePayer': string | null;
    /**
     * - The number of lamports the `taker` or `payer` has to pay for account rent, if a valid transaction is returned - Note that this value is just an estimate - JupiterZ\'s MM currently does not cover for rent fees 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'rentFeeLamports': number;
    /**
     * - The public key of the account that will cover the rent fee, it can be either `taker` or `payer` if passed in - JupiterZ\'s MM currently does not cover for rent fees 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'rentFeePayer': string | null;
    /**
     * - Deprecated, in favour of router 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'swapType': string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'router': OrderGet200ResponseRouterEnum;
    /**
     * - Unsigned base-64 encoded transaction to be signed and used in `/execute` - If `taker` is null, this field will be null. - If the `transaction` field is empty, it is returned with `errorCode` and `errorMessage` such as Insufficient Funds 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'transaction': string | null;
    /**
     * 
     * @type {boolean}
     * @memberof OrderGet200Response
     */
    'gasless': boolean;
    /**
     * - Required to make a request to `/execute` 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'requestId': string;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'totalTime': number;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'taker': string | null;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'quoteId'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'maker'?: string;
    /**
     * 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'expireAt'?: string;
    /**
     * - This field will be present if `taker` is defined and `transaction` is an empty string - It is unique for each error scenarios 
     * @type {number}
     * @memberof OrderGet200Response
     */
    'errorCode'?: OrderGet200ResponseErrorCodeEnum;
    /**
     * - This field will be present if `taker` is defined and `transaction` is an empty string - This field can still return despite having a valid order/quote - This is meant for display purposes only and it is discouraged to match these error messages as they could be parameterized 
     * @type {string}
     * @memberof OrderGet200Response
     */
    'errorMessage'?: OrderGet200ResponseErrorMessageEnum;
}

export const OrderGet200ResponseRouterEnum = {
    IRIS: 'iris',
    JUPITERZ: 'jupiterz',
    DFLOW: 'dflow',
    OKX: 'okx'
} as const;

export type OrderGet200ResponseRouterEnum = typeof OrderGet200ResponseRouterEnum[keyof typeof OrderGet200ResponseRouterEnum];
export const OrderGet200ResponseErrorCodeEnum = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;

export type OrderGet200ResponseErrorCodeEnum = typeof OrderGet200ResponseErrorCodeEnum[keyof typeof OrderGet200ResponseErrorCodeEnum];
export const OrderGet200ResponseErrorMessageEnum = {
    INSUFFICIENT_FUNDS: 'Insufficient funds',
    TOP_UP_SOL_AMOUNT_SOL_FOR_GAS: 'Top up `${solAmount}` SOL for gas',
    MINIMUM_SWAP_AMOUNT_FOR_GASLESS: 'Minimum `${swapAmount}` for gasless'
} as const;

export type OrderGet200ResponseErrorMessageEnum = typeof OrderGet200ResponseErrorMessageEnum[keyof typeof OrderGet200ResponseErrorMessageEnum];


