/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [Get Order](/docs/ultra/get-order) | | [Execute Order](/docs/ultra/execute-order) | 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrderGet500Response
 */
export interface OrderGet500Response {
    /**
     * 
     * @type {string}
     * @memberof OrderGet500Response
     */
    'error': string;
}

