/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [Get Order](/docs/ultra/get-order) | | [Execute Order](/docs/ultra/execute-order) | 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { OrderGet200ResponseRoutePlanInnerSwapInfo } from './order-get200-response-route-plan-inner-swap-info';

/**
 * 
 * @export
 * @interface OrderGet200ResponseRoutePlanInner
 */
export interface OrderGet200ResponseRoutePlanInner {
    /**
     * 
     * @type {OrderGet200ResponseRoutePlanInnerSwapInfo}
     * @memberof OrderGet200ResponseRoutePlanInner
     */
    'swapInfo': OrderGet200ResponseRoutePlanInnerSwapInfo;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200ResponseRoutePlanInner
     */
    'percent': number;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200ResponseRoutePlanInner
     */
    'bps': number;
    /**
     * 
     * @type {number}
     * @memberof OrderGet200ResponseRoutePlanInner
     */
    'usdValue'?: number;
}

