/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [Get Order](/docs/ultra/get-order) | | [Execute Order](/docs/ultra/execute-order) | 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ShieldGet200ResponseWarningsValueInner
 */
export interface ShieldGet200ResponseWarningsValueInner {
    /**
     * - Type of warning for the token 
     * @type {string}
     * @memberof ShieldGet200ResponseWarningsValueInner
     */
    'type'?: ShieldGet200ResponseWarningsValueInnerTypeEnum;
    /**
     * - Human-readable warning message 
     * @type {string}
     * @memberof ShieldGet200ResponseWarningsValueInner
     */
    'message'?: string;
    /**
     * - Severity level of the warning 
     * @type {string}
     * @memberof ShieldGet200ResponseWarningsValueInner
     */
    'severity'?: ShieldGet200ResponseWarningsValueInnerSeverityEnum;
    /**
     * - Optional external source of the warning 
     * @type {string}
     * @memberof ShieldGet200ResponseWarningsValueInner
     */
    'source'?: ShieldGet200ResponseWarningsValueInnerSourceEnum;
}

export const ShieldGet200ResponseWarningsValueInnerTypeEnum = {
    NOT_VERIFIED: 'NOT_VERIFIED',
    LOW_LIQUIDITY: 'LOW_LIQUIDITY',
    NOT_SELLABLE: 'NOT_SELLABLE',
    LOW_ORGANIC_ACTIVITY: 'LOW_ORGANIC_ACTIVITY',
    HAS_MINT_AUTHORITY: 'HAS_MINT_AUTHORITY',
    HAS_FREEZE_AUTHORITY: 'HAS_FREEZE_AUTHORITY',
    HAS_PERMANENT_DELEGATE: 'HAS_PERMANENT_DELEGATE',
    NEW_LISTING: 'NEW_LISTING',
    VERY_LOW_TRADING_ACTIVITY: 'VERY_LOW_TRADING_ACTIVITY',
    HIGH_SUPPLY_CONCENTRATION: 'HIGH_SUPPLY_CONCENTRATION',
    NON_TRANSFERABLE: 'NON_TRANSFERABLE',
    MUTABLE_TRANSFER_FEES: 'MUTABLE_TRANSFER_FEES',
    SUSPICIOUS_DEV_ACTIVITY: 'SUSPICIOUS_DEV_ACTIVITY',
    SUSPICIOUS_TOP_HOLDER_ACTIVITY: 'SUSPICIOUS_TOP_HOLDER_ACTIVITY',
    HIGH_SINGLE_OWNERSHIP: 'HIGH_SINGLE_OWNERSHIP',
    TRANSFER_FEES: '{}%_TRANSFER_FEES'
} as const;

export type ShieldGet200ResponseWarningsValueInnerTypeEnum = typeof ShieldGet200ResponseWarningsValueInnerTypeEnum[keyof typeof ShieldGet200ResponseWarningsValueInnerTypeEnum];
export const ShieldGet200ResponseWarningsValueInnerSeverityEnum = {
    INFO: 'info',
    WARNING: 'warning',
    CRITICAL: 'critical'
} as const;

export type ShieldGet200ResponseWarningsValueInnerSeverityEnum = typeof ShieldGet200ResponseWarningsValueInnerSeverityEnum[keyof typeof ShieldGet200ResponseWarningsValueInnerSeverityEnum];
export const ShieldGet200ResponseWarningsValueInnerSourceEnum = {
    RUG_CHECK: 'RugCheck'
} as const;

export type ShieldGet200ResponseWarningsValueInnerSourceEnum = typeof ShieldGet200ResponseWarningsValueInnerSourceEnum[keyof typeof ShieldGet200ResponseWarningsValueInnerSourceEnum];


