/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [Get Order](/docs/ultra/get-order) | | [Execute Order](/docs/ultra/execute-order) | 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ShieldGet200ResponseWarningsValueInner } from './shield-get200-response-warnings-value-inner';

/**
 * 
 * @export
 * @interface ShieldGet200Response
 */
export interface ShieldGet200Response {
    /**
     * 
     * @type {{ [key: string]: Array<ShieldGet200ResponseWarningsValueInner>; }}
     * @memberof ShieldGet200Response
     */
    'warnings': { [key: string]: Array<ShieldGet200ResponseWarningsValueInner>; };
}

