/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [V1](/docs/tokens/v1) | | [V2](/docs/tokens/v2) | | [V1 Deprecated](/docs/tokens/v1) | 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MintInformationAudit
 */
export interface MintInformationAudit {
    /**
     * 
     * @type {boolean}
     * @memberof MintInformationAudit
     */
    'isSus'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof MintInformationAudit
     */
    'mintAuthorityDisabled'?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof MintInformationAudit
     */
    'freezeAuthorityDisabled'?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof MintInformationAudit
     */
    'topHoldersPercentage'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MintInformationAudit
     */
    'devBalancePercentage'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof MintInformationAudit
     */
    'devMigrations'?: number | null;
}

