/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [V1](/docs/tokens/v1) | | [V2](/docs/tokens/v2) | | [V1 Deprecated](/docs/tokens/v1) | 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SearchGet400Response
 */
export interface SearchGet400Response {
    /**
     * 
     * @type {string}
     * @memberof SearchGet400Response
     */
    'error': string;
}

