/* tslint:disable */
/* eslint-disable */
/**
 * Quickstart
 * | Link | | --- | | [V1](/docs/tokens/v1) | | [V2](/docs/tokens/v2) | | [V1 Deprecated](/docs/tokens/v1) | 
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SwapStats
 */
export interface SwapStats {
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'priceChange'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'holderChange'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'liquidityChange'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'volumeChange'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'buyVolume'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'sellVolume'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'buyOrganicVolume'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'sellOrganicVolume'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'numBuys'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'numSells'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'numTraders'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'numOrganicBuyers'?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SwapStats
     */
    'numNetBuyers'?: number | null;
}

